config/routes.rb
Rails.application.routes.draw do

  resources :notices

  resources :conversations do
    resources :messages
  end

  get 'conversations/admin' => 'conversations#admin'

  get 'legal/privacy' => "legal#privacy"
  get 'legal/using' => "legal#using"
  #PROFILE------FOLLOW/UNFOLLOW
  get 'profiles/:id/follow' => 'follows#profile_follow', as: 'profile_follow'

  ##SEARCH------resources :zizuminfos 보다 위에
  get 'zizuminfos/search/' => "zizuminfos#search"
  post 'zizuminfos/getZizum' => "zizuminfos#getZizum"
  get 'zizuminfos/getGungu' => "menus#getGungu"
  get 'zizuminfos/zizummenus' => "zizuminfos#zizummenus"
  get 'zizuminfos/:id/show' => "zizuminfos#show"
  #밑에 꺼 꼭 넣어야함.
  get 'zizuminfos/index' => "zizuminfos#index", as: 'zizuminfos'
  ##-------------------------------------


  #SEARCH----------resouces :menus 보다 위에 가게 해야 함! --------------------
  get 'restaurants/search' => "restaurants#search"
  get 'menus/search/' => "menus#search"
  get 'menus/getGungu' => "menus#getGungu"
  get 'menus/menus/getGungu' => "menus#getGungu"
  get 'zizuminfos/getGungu' => "menus#getGungu"
  #밑에 꺼 꼭 넣어야함.
  get 'menus/index' => "menus#index", as: 'menus'
  #--------------------------------------------------------------------------

  #-----------------좋아요 ajax
  get 'follows/zizumfollow' => "follows#zizumfollow"
  get 'follows/recipefollow' => "follows#recipefollow"
  
  #-----------admin 관리 페이지
  get 'admincontrol/index' => "admincontrol#index"
  get 'admincontrol/zizuminfo' => "admincontrol#zizuminfo"
  get 'admincontrol/menu' => "admincontrol#menu"
  get 'admincontrol/restaurant' => "admincontrol#restaurant"
  get 'admincontrol/zizumupdate' => "admincontrol#zizumupdate"
  get 'admincontrol/resupdate' => "admincontrol#resupdate"
  get 'admincontrol/menuupdate' => "admincontrol#menuupdate"
  #===============메뉴별 제보 요청==============
 get 'userrequests/index'

 get 'userrequests/new'

 get 'userrequests/ask'

 get 'edit_asks/index'
 
 get 'edit_asks/ask'
  ## 수정 / 삭제 요청 ###
  #요청 확인
  get '/userrequests' => 'userrequests#index'
  #메뉴 추가 요청
  get '/userrequests/new_request' => 'userrequests#new_request'
  post '/userrequests/create' => 'userrequests#create'
  #메뉴 수청 / 삭제 요청
  get '/userrequests/edit_request' => 'userrequests#edit_request'
  post '/userrequests/edit_request' => 'userrequests#edit_request'
  #승인
  post '/userrequests/permit' => 'userrequests#permit'
  #=================================
  
  # 나만의 페이지
  resources :profiles
  # post '/profiles/:id/myposts' => 'profiles#myposts'
  scope 'profiles/:id' do
    get 'myposts', :to => 'profiles#myposts'
    get 'mycomments', :to => 'profiles#mycomments'
    get 'myrequests', :to => 'profiles#myrequests'    
  end
  get '/zizuminfos/:id/follow_destroy', to: 'follows#profile_follow_destroy_toggle', as: 'profile_follow_destroy'

  # # Follow 기능
  # post '/zizuminfos/:id/follow', to: 'follows#zizum_back_follow_toggle', as: 'zizum_back_follow'
  # post '/menus/index/params', to: 'follows#zizum_front_follow_toggle', as: 'zizum_front_follow'

  # freeboards 용
    post "/checkNum" => "freeboards#checkNum"

    # get '/freeboards/'
  resources :recipes
  resources :freeboards
  resources :userrequests
  resources :zizuminfos
  resources :restaurants
  resources :menus

  get 'home/index'
  root 'home#index'

  #============크롤링===============
  get '/crawling' => 'restaurants#crawling'
  #================================
  post '/tinymce_assets' => 'tinymce_assets#create'
  # user
  # post '/users/checkDouble' => 'user/registrations#checkDouble'
  # post "/users/checkDouble" => "user/registrations#checkDouble" 
  devise_scope :user do
     post "/users/checkDouble" => "user/registrations#checkDouble" 
     post "/checkDouble" => "user/registrations#checkDouble"
     get "/users" => 'user/registrations#new'
  end
  devise_for :users, :controllers => {registrations: 'user/registrations',passwords: 'users/passwords' }
  # devise_scope :user do
  #   get 'editsns', :to => 'devise/registrations#editsns'
  # end
  # resources :comments, only: [:create, :destroy]
  resources :comments do
    member do
      put "like", to: "comments#like"
      put "unvote", to: "comments#unvote" 
      put "dislike", to: "comments#dislike"    
    end    
  end


  # 알림
  # get '/new_alarms/read_all' => 'new_alarms#read_all'
  # resources :new_alarms #순서이대로
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'# 맨아래에 둬주세요
  
  # concern :paginatable do
  #   get '(page/:page)', action: :index, on: :collection, as: ''
  # end
  
  # resources :my_resources, concerns: :paginatable
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notice.rb
class Notice < ApplicationRecord
    belongs_to :user
    acts_as_commentable
    is_impressionable

    def time(post)
        if Time.now.strftime("%m:%d") == post.created_at.strftime("%m:%d")
          post.created_at.strftime("%H:%m")
        else
          post.created_at.strftime("%m-%d")
        end
    end  
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]
  before_action :authorize_admin, except: [:index, :show]
  # 조회수
  impressionist actions: [:show]
  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.all
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/new
  def new
    @notice = Notice.new
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)
    if current_user.admin?
      @notice.user = current_user
    end
    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render :new }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to notices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notice_params
      params.require(:notice).permit(:title, :content,:user,:image,:isModal)
    end
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/notices/_form.html.erb
<%# 
<%= simple_form_for(@notice) do |f| %>
  <%# <%= f.error_notification %>
  <%# <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %> 


<%= form_with(model:  notice, local: true) do |form| %>

  <% if  notice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize( notice.errors.count, "error") %> prohibited this  notice from being saved:</h2>

      <ul>
      <%  notice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="field form-inline">
      <%= form.label '제목' %>
      <%= form.text_field :title, :class =>"form-control" ,:style=>"width:95%;margin-left:10px;margin-top:10px;", :required=>'true'%>
    </div><br/>

    <div class="field">
        <%= form.label '내용' %>
        <%= tinymce :language => "en",:relative_urls => false %>    
        <%= form.text_area :content, :class => "form-control tinymce", :rows=> "10"%>
    </div>

    <div class="field">
        <%= form.label '팝업 설정' %>
        <%= form.check_box :isModal %>
    </div>

  <div class="actions">
    <%= form.submit %>
  </div>


<% end %>

app/views/notices/edit.html.erb
<h1>Editing Notice</h1>

<%= render 'form', notice: @notice %>

<%= link_to 'Show', @notice %> |
<%= link_to 'Back', notices_path %>

app/views/notices/index.html.erb
<div class="post-contents container">
  <div class="big-title">공지사항</div>
</div>
<div class ="contents">
    <div class="post-num">
      총 <%=Notice.all.count%>건
    </div>
    <div class="post-table" style="margin-top: 0.8rem; margin-bottom: 5rem;">    
      <table class="table table-hover" id="post-table">
        <thead>
          <tr>     
            <th style="width:8%;">No</th>
            <th style="width:58%;" class="title">제목</th>
            <th>작성자</th>
            <th style="width:10%;">작성일</th>
            <th style="width:8%;">조회수</th>      
          </tr>
        </thead>

        <tbody>
      </div>
      <%n=1%>
        <% @notices.each do | notice| %>
          <tr>
            <td><%=n%><%n=n+1%></td>
            <td class="title form-inline"><div class="ctg"style="font-weight:lighter;font-size:0.6rem;"><%= link_to  notice.title,  notice, {:class => "linkto",:style=>"font-size:0.8rem;"} %></td>
            <td>관리자</td>
            <td><%=  notice.time( notice)%></td>                
            <td> <%=  notice.impressionist_count(:filter=>:session_hash) %></td>
          </tr>
        <% end %>
     </tbody>
  </table>
  </div>
<br>
<% if user_signed_in? &&current_user.admin?%>
<%= button_to '공지 등록', new_notice_path,:method=>'get' %>
<%end%>

<script>
// 행 clickable 
$(document).ready(function() {
    $('#post-table tr').click(function() {
        var href = $(this).find("a").attr("href");

        if(href) {
            window.location = href;
        }
    });
});
 </script>

app/views/notices/new.html.erb
<% if user_signed_in?&& current_user.admin?%>
<div class= "post index-contents rtnt">
    <div class="new-post" > 
        <b>공지사항 등록</b>  
        <p style = "font-weight:lighter;">관리자만 공지사항을 등록할 수 있습니다.</p>
    </div>
        <%= render 'form', notice: @notice %>
        <div class="back-btn">
            <%= link_to '취소', @notice, class:"linkto" %>
        </div>
</div>
<% end %>

app/views/notices/show.html.erb
<div class="post-contents container">
 공지사항           
</div>

<div class ="contents">
  <div class="back container"><%= link_to '뒤로가기',  notices_path, class:"post-linkto"%></div>
  <div class="container">
    <div class="post-view">
        <p style="color:#FF5400;">공지사항</p>
        <h5 class="post-title nago"> <%= @notice.title %></h5>
        <div class="form-inline">
         <%=image_tag("beige-logo.PNG", class:"post-profile-img")%>        
         <div>관리자</div> 
         <div style="font-weight:lighter;margin-left:2rem;"><%= @notice.created_at.strftime("%Y-%m-%d") %> </div>
         <%# <div style="margin-left:auto;font-size:0.8rem;"> 조회수: <%= @ notice.impressionist_count(:filter=>:session_hash) %>
        </div>      

      <hr/>
        <%# <p><%= @notice.content.html_safe  %>
        <p><%= content_tag(:div, @notice.content.html_safe, :class=>"post-body")  %></p>
        
        <div class="post-edit">
          <% if user_signed_in? && current_user.admin?%>
            <%= link_to '수정', edit_notice_path(@notice), class:"linkto" %>
            <%= link_to '삭제', @notice, method: :delete, class:"linkto"%>      
          <%end%>  
        </div>
    </div>
 
  </div>                
</div>                