config/routes.rb
Rails.application.routes.draw do

  resources :notices

  resources :conversations do
    resources :messages
  end

  get 'conversations/admin' => 'conversations#admin'

  get 'legal/privacy' => "legal#privacy"
  get 'legal/using' => "legal#using"
  #PROFILE------FOLLOW/UNFOLLOW
  get 'profiles/:id/follow' => 'follows#profile_follow', as: 'profile_follow'

  ##SEARCH------resources :zizuminfos 보다 위에
  get 'zizuminfos/search/' => "zizuminfos#search"
  post 'zizuminfos/getZizum' => "zizuminfos#getZizum"
  get 'zizuminfos/getGungu' => "menus#getGungu"
  get 'zizuminfos/zizummenus' => "zizuminfos#zizummenus"
  get 'zizuminfos/:id/show' => "zizuminfos#show"
  #밑에 꺼 꼭 넣어야함.
  get 'zizuminfos/index' => "zizuminfos#index", as: 'zizuminfos'
  ##-------------------------------------


  #SEARCH----------resouces :menus 보다 위에 가게 해야 함! --------------------
  get 'restaurants/search' => "restaurants#search"
  get 'menus/search/' => "menus#search"
  get 'menus/getGungu' => "menus#getGungu"
  get 'menus/menus/getGungu' => "menus#getGungu"
  get 'zizuminfos/getGungu' => "menus#getGungu"
  #밑에 꺼 꼭 넣어야함.
  get 'menus/index' => "menus#index", as: 'menus'
  #--------------------------------------------------------------------------

  #-----------------좋아요 ajax
  get 'follows/zizumfollow' => "follows#zizumfollow"
  get 'follows/recipefollow' => "follows#recipefollow"
  
  #-----------admin 관리 페이지
  get 'admincontrol/index' => "admincontrol#index"
  get 'admincontrol/zizuminfo' => "admincontrol#zizuminfo"
  get 'admincontrol/menu' => "admincontrol#menu"
  get 'admincontrol/restaurant' => "admincontrol#restaurant"
  get 'admincontrol/zizumupdate' => "admincontrol#zizumupdate"
  get 'admincontrol/resupdate' => "admincontrol#resupdate"
  get 'admincontrol/menuupdate' => "admincontrol#menuupdate"
  #===============메뉴별 제보 요청==============
 get 'userrequests/index'

 get 'userrequests/new'

 get 'userrequests/ask'

 get 'edit_asks/index'
 
 get 'edit_asks/ask'
  ## 수정 / 삭제 요청 ###
  #요청 확인
  get '/userrequests' => 'userrequests#index'
  #메뉴 추가 요청
  get '/userrequests/new_request' => 'userrequests#new_request'
  post '/userrequests/create' => 'userrequests#create'
  #메뉴 수청 / 삭제 요청
  get '/userrequests/edit_request' => 'userrequests#edit_request'
  post '/userrequests/edit_request' => 'userrequests#edit_request'
  #승인
  post '/userrequests/permit' => 'userrequests#permit'
  #=================================
  
  # 나만의 페이지
  resources :profiles
  # post '/profiles/:id/myposts' => 'profiles#myposts'
  scope 'profiles/:id' do
    get 'myposts', :to => 'profiles#myposts'
    get 'mycomments', :to => 'profiles#mycomments'
    get 'myrequests', :to => 'profiles#myrequests'    
  end
  get '/zizuminfos/:id/follow_destroy', to: 'follows#profile_follow_destroy_toggle', as: 'profile_follow_destroy'

  # # Follow 기능
  # post '/zizuminfos/:id/follow', to: 'follows#zizum_back_follow_toggle', as: 'zizum_back_follow'
  # post '/menus/index/params', to: 'follows#zizum_front_follow_toggle', as: 'zizum_front_follow'

  # freeboards 용
    post "/checkNum" => "freeboards#checkNum"

    # get '/freeboards/'
  resources :recipes
  resources :freeboards
  resources :userrequests
  resources :zizuminfos
  resources :restaurants
  resources :menus

  get 'home/index'
  root 'home#index'

  #============크롤링===============
  get '/crawling' => 'restaurants#crawling'
  #================================
  post '/tinymce_assets' => 'tinymce_assets#create'
  # user
  # post '/users/checkDouble' => 'user/registrations#checkDouble'
  # post "/users/checkDouble" => "user/registrations#checkDouble" 
  devise_scope :user do
     post "/users/checkDouble" => "user/registrations#checkDouble" 
     post "/checkDouble" => "user/registrations#checkDouble"
     get "/users" => 'user/registrations#new'
  end
  devise_for :users, :controllers => {registrations: 'user/registrations',passwords: 'users/passwords' }
  # devise_scope :user do
  #   get 'editsns', :to => 'devise/registrations#editsns'
  # end
  # resources :comments, only: [:create, :destroy]
  resources :comments do
    member do
      put "like", to: "comments#like"
      put "unvote", to: "comments#unvote" 
      put "dislike", to: "comments#dislike"    
    end    
  end


  # 알림
  # get '/new_alarms/read_all' => 'new_alarms#read_all'
  # resources :new_alarms #순서이대로
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'# 맨아래에 둬주세요
  
  # concern :paginatable do
  #   get '(page/:page)', action: :index, on: :collection, as: ''
  # end
  
  # resources :my_resources, concerns: :paginatable
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admincontrol_controller.rb
class AdmincontrolController < ApplicationController
    before_action :authorize_admin

    def index
    end
    
    def zizuminfo
        @zizuminfos = Zizuminfo.all
    end

    def restaurant
        @restaurants = Restaurant.all
    end

    def zizumupdate
        puts "=============="
        puts params[:zizum]
        if params[:zizum] == "zizumall"
            Zizuminfo.Subway        #1
            Zizuminfo.Momstouch     #2
            # Zizuminfo.Raracost
            Zizuminfo.Vips          #3
            Zizuminfo.Coffeebean    #4
            Zizuminfo.Popeyes       #5
            Zizuminfo.Baskin        #6
            #Zizuminfo.PizzaSchool   #7
            Zizuminfo.SeasonsTable  #8
            #Zizuminfo.Burgerking    #9
            Zizuminfo.DunkinDonuts  #10   
        end

        redirect_to admincontrol_zizuminfo_path
    end

    def resupdate
        res = params[:res]
        puts params[:res]
        if res == "resall"
            Restaurant.RestaurantName
        elsif res == "서브웨이"
            Zizuminfo.Subway
        elsif res =="맘스터치"
            Zizuminfo.Momstouch
        elsif res == "라라코스트"
            Zizuminfo.Raracost
        elsif res == "빕스"
            Zizuminfo.Vips
        elsif res == "커피빈"
            Zizuminfo.Coffeebean
        elsif res == "파파이스"
            Zizuminfo.Popeyes
        elsif res == "배스킨라빈스"
            Zizuminfo.Baskin
        # elsif res == "피자스쿨"
        #     Zizuminfo.PizzaSchool
        elsif res == "계절밥상"
            Zizuminfo.SeasonsTable
        #elsif res == "버거킹"
        #    Zizuminfo.Burgerking
        elsif res == "던킨도너츠"
            Zizuminfo.DunkinDonuts
        end


        redirect_to admincontrol_restaurant_path
    end


    def menu
        @restaurants = Restaurant.all
    end

    def menuupdate
        res = params[:res]
        puts params[:res]
        if res == "resall"
            Menu.Subway        #1
            Menu.Momstouch     #2
            # Menu.Raracost
            Menu.Vips          #3
            Menu.Coffeebean    #4
            Menu.Popeyes       #5
            Menu.Baskin        #6
            Menu.PizzaSchool   #7
            Menu.SeasonsTable  #8
            #Menu.Burgerking    #9
            Menu.DunkinDonuts  #10   
        elsif res == "서브웨이"
            Menu.Subway
        elsif res =="맘스터치"
            Menu.Momstouch
        elsif res == "라라코스트"
            Menu.Raracost
        elsif res == "빕스"
            Menu.Vips
        elsif res == "커피빈"
            Menu.Coffeebean
        elsif res == "파파이스"
            Menu.Popeyes
        elsif res == "배스킨라빈스"
            Menu.Baskin
        elsif res == "피자스쿨"
            Menu.PizzaSchool
        elsif res == "계절밥상"
            Menu.SeasonsTable
        #elsif res == "버거킹"
        #    Menu.Burgerking
        elsif res == "던킨도너츠"
            Menu.DunkinDonuts
        end


        redirect_to admincontrol_menu_path
    end

end

app/helpers/admincontrol_helper.rb
module AdmincontrolHelper
end

app/views/admincontrol/_category.html.erb
<div class="admin-index-upper container">
    <div class="admin-index-category-box row">
        <%=link_to admincontrol_index_path, class:"col-6 col-sm-3 col-md-3 admin-index-category admin-index-all-ct" do%>
            <div>관리 전체</div>
        <%end%>

        <%=link_to admincontrol_restaurant_path, class:"col-6 col-sm-3 col-md-3 admin-index-category admin-index-res-ct" do%>
            <div>식당 관리</div>
        <%end%>
    
        <%=link_to admincontrol_zizuminfo_path, class:"col-6 col-sm-3 col-md-3 admin-index-category admin-index-zizum-ct"  do%>
            <div>지점 관리</div>
        <%end%>

        <%=link_to admincontrol_menu_path, class:"col-6 col-sm-3 col-md-3 admin-index-category admin-index-user-ct"  do%>
            <div>메뉴 관리</div>
        <%end%>
    </div>
</div>

app/views/admincontrol/index.html.erb
<div class="admin-body">
    <%if user_signed_in? && current_user.admin?%>
       <%=render partial: 'admincontrol/category'%>

        <div><%= link_to "전체 크롤링 업데이트", "/crawling"%></div>
        <div class="admin-index-content-stretch">
            <div class="admin-index-content-box container">
                <div class="admin-index-content-title middle-title">최근 관리 항목</div>
                
                <div class="d-flex justify-content-center">
                <div class="admin-index-recent-container">
                    <div class="admin-index-recent-wrap">
                        <div class="small-title"><i class="fas fa-utensils"></i>&nbsp;식당 관리</div>
                        <div class="admin-index-recent-box"></div>
                    </div>

                    <div class="admin-index-recent-wrap">
                        <div class="small-title"><i class="fas fa-store"></i>&nbsp;식당 관리</div>
                        <div class="admin-index-recent-box"></div>
                    </div>

                    <div class="admin-index-recent-wrap">
                        <div class="small-title"><i class="fas fa-users"></i>&nbsp;식당 관리</div>
                        <div class="admin-index-recent-box"></div>
                    </div>

                </div>
                </div>
            </div>
        </div>

    <%else%>
        <div class="admin-index-inner container">
            접근 권한이 없습니다.
        </div>
    <%end%>
</div>

<script>
    $(".admin-index-all-ct").addClass("admin-index-activebtn")
    $(".admin-index-category").not(".admin-index-all-ct").removeClass("admin-index-activebtn")
   
</script>

app/views/admincontrol/menu.html.erb
<div class="admin-body">
    <%if user_signed_in? && current_user.admin?%>
       <%=render partial: 'admincontrol/category'%>
        <div class="admin-index-content-stretch">
            <div class="admin-index-content-box container">
                <div class="admin-index-content-title middle-title">식당 관리</div>
                
                <div class="d-flex justify-content-center">
                    <div class="admin-index-recent-container">
                        <table class="table admin-res-list">
                            <thead>
                                <tr>
                                    <th width="20%">식당 번호</th>
                                    <th width="40%">식당 이름</th>
                                    <th width="40%">메뉴 업데이트</th>
                                </tr>
                            </thead>
                            <tbody>
                            <%@restaurants.each do |restaurant|%>
                                <tr class="admin-res-box">
                                    <td><%=restaurant.id%></td>
                                    <td><%=link_to restaurant.restaurant_name, restaurant_path(restaurant)%></td>
                                    <td><span class="res-menu-update" id="<%=restaurant.restaurant_name%>">모든 메뉴정보업데이트</span></td>
                                </tr>
                            <%end%>
                            </tbody>  
                        </table>

                        <div class="admin-res-subfunc">
                            <%=link_to "레스토랑 추가", new_restaurant_path%>
                            <%=link_to "메뉴 전체 크롤링", admincontrol_menuupdate_path, class:"menuall"%>
                        </div>
                    </div>
                </div>
            
            </div>
        </div>
        

    <%else%>
        <div class="admin-index-inner container">
            접근 권한이 없습니다.
        </div>
    <%end%>
</div>

<script>
    $(".admin-index-user-ct").addClass("admin-index-activebtn")
    $(".admin-index-category").not(".admin-index-user-ct").removeClass("admin-index-activebtn")
   
   $(".menuall").click(function () {
        $res = $(this).attr("class")
        alert("업데이트 중입니다. 기다려주세요")
        $.ajax({
        async : true,
        data : {res : $res},
        type : "GET",
        url : "menuupdate",
        success : function(data){
           
             alert("모든 식당의 메뉴 업데이트 완료")
        }
        });  
    })

    $(".res-menu-update").click(function () {
        $res = $(this).attr("id")
        $select = $(this)
        alert("업데이트 중입니다. 기다려주세요")
        $.ajax({
        async : true,
        data : {res : $res},
        type : "GET",
        url : "menuupdate",
        success : function(data){
            
            alert($res+" 메뉴 업데이트 완료")
        }
        });  
    })
    
</script>

app/views/admincontrol/restaurant.html.erb
<div class="admin-body">
    <%if user_signed_in? && current_user.admin?%>
       <%=render partial: 'admincontrol/category'%>
        <div class="admin-index-content-stretch">
            <div class="admin-index-content-box container">
                <div class="admin-index-content-title middle-title">식당 관리</div>
                
                <div class="d-flex justify-content-center">
                    <div class="admin-index-recent-container">
                        <table class="table admin-res-list">
                            <thead>
                                <tr>
                                    <th width="15%">식당 번호</th>
                                    <th width="35%">식당 이름</th>
                                    <th width="25%">식당 정보수정</th>
                                    <th width="25%">지점업데이트</th>
                                </tr>
                            </thead>
                            <tbody>
                            <%@restaurants.each do |restaurant|%>
                                <tr class="admin-res-box">
                                    <td><%=restaurant.id%></td>
                                    <td><%=link_to restaurant.restaurant_name, restaurant_path(restaurant)%></td>
                                    <td><%=link_to "식당정보수정", edit_restaurant_path(restaurant)%></td>
                                    <td><span class="res-zizum-update" id="<%=restaurant.restaurant_name%>">지점정보업데이트</span></td>
                                </tr>
                            <%end%>
                            </tbody>  
                        </table>

                        <div class="admin-res-subfunc">
                            <%=link_to "레스토랑 추가", new_restaurant_path%>
                            <%=link_to "식당 전체 크롤링", admincontrol_resupdate_path, class:"resall"%>
                        </div>
                    </div>
                </div>
            
            </div>
        </div>
        

    <%else%>
        <div class="admin-index-inner container">
            접근 권한이 없습니다.
        </div>
    <%end%>
</div>

<script>
    $(".admin-index-res-ct").addClass("admin-index-activebtn")
    $(".admin-index-category").not(".admin-index-res-ct").removeClass("admin-index-activebtn")
   
    $(".resall").click(function () {
        $res = $(this).attr("class")
         alert("업데이트 중입니다. 기다려주세요")
        $.ajax({
        async : true,
        data : {res : $res},
        type : "GET",
        url : "resupdate",
        success : function(data){
            alert("모든 식당 업데이트")
        }
        });  
    })

    $(".res-zizum-update").click(function () {
        $res = $(this).attr("id")
         alert("업데이트 중입니다. 기다려주세요")
        $.ajax({
        async : true,
        data : {res : $res},
        type : "GET",
        url : "resupdate",
        success : function(data){
             alert($res+" 지점 업데이트 완료")
        }
        });  
    })
   
</script>

app/views/admincontrol/zizuminfo.html.erb
<div class="admin-body">
    <%if user_signed_in? && current_user.admin?%>
       <%=render partial: 'admincontrol/category'%>
        <div class="admin-index-content-stretch">
            <div class="admin-index-content-box container">
                <div class="admin-index-content-title middle-title">지점 관리</div>
                
                <div class="d-flex justify-content-center">
                    <div class="admin-index-recent-container">
                        <table class="table admin-ziz-list">
                            <thead>
                                <tr>
                                    <th width="10%">#</th>
                                    <th width="20%">식당 이름</th>
                                    <th width="45%">지점 이름</th>
                                    <th width="25%">정보 업데이트</th>
                                </tr>
                            </thead>
                            <tbody>
                            <%@zizuminfos.each do |zizum|%>
                                <tr class="admin-res-box">
                                    <td><%=zizum.id%></td>
                                    <td><%=link_to zizum.restaurant_name, restaurant_path(zizum.restaurant)%></td>
                                    <td><%=link_to zizum.zizum_name, zizuminfo_path(zizum)%></td>
                                    <td><%=link_to "수정하기", edit_zizuminfo_path(zizum)%></td>
                                </tr>
                            <%end%>
                            </tbody>  
                        </table>

                        <div class="admin-res-subfunc">
                            <div>지점 추가를 하시려면 /admin 으로 이동하세요</div>
                            <%=link_to "모든 식당의 지점 정보 업데이트", admincontrol_zizumupdate_path, class:"zizumall"%>
                        </div>
                    </div>
                </div>
            
            </div>
        </div>
        

    <%else%>
        <div class="admin-index-inner container">
            접근 권한이 없습니다.
        </div>
    <%end%>
</div>

<script>
    $(".admin-index-zizum-ct").addClass("admin-index-activebtn")
    $(".admin-index-category").not(".admin-index-zizum-ct").removeClass("admin-index-activebtn")

     $(".zizumall").click(function () {
        $zizum = $(this).attr("class")
        console.log($zizum)
        alert("업데이트 중입니다. 기다려주세요")
        $.ajax({
        async : true,
        data : {zizum : $zizum},
        type : "GET",
        url : "zizumupdate",
        success : function(data){
            
           alert("지점 업데이트 완료")
        }
        });  
    })
</script>