config/routes.rb
Rails.application.routes.draw do

  resources :notices

  resources :conversations do
    resources :messages
  end

  get 'conversations/admin' => 'conversations#admin'

  get 'legal/privacy' => "legal#privacy"
  get 'legal/using' => "legal#using"
  #PROFILE------FOLLOW/UNFOLLOW
  get 'profiles/:id/follow' => 'follows#profile_follow', as: 'profile_follow'

  ##SEARCH------resources :zizuminfos 보다 위에
  get 'zizuminfos/search/' => "zizuminfos#search"
  post 'zizuminfos/getZizum' => "zizuminfos#getZizum"
  get 'zizuminfos/getGungu' => "menus#getGungu"
  get 'zizuminfos/zizummenus' => "zizuminfos#zizummenus"
  get 'zizuminfos/:id/show' => "zizuminfos#show"
  #밑에 꺼 꼭 넣어야함.
  get 'zizuminfos/index' => "zizuminfos#index", as: 'zizuminfos'
  ##-------------------------------------


  #SEARCH----------resouces :menus 보다 위에 가게 해야 함! --------------------
  get 'restaurants/search' => "restaurants#search"
  get 'menus/search/' => "menus#search"
  get 'menus/getGungu' => "menus#getGungu"
  get 'menus/menus/getGungu' => "menus#getGungu"
  get 'zizuminfos/getGungu' => "menus#getGungu"
  #밑에 꺼 꼭 넣어야함.
  get 'menus/index' => "menus#index", as: 'menus'
  #--------------------------------------------------------------------------

  #-----------------좋아요 ajax
  get 'follows/zizumfollow' => "follows#zizumfollow"
  get 'follows/recipefollow' => "follows#recipefollow"
  
  #-----------admin 관리 페이지
  get 'admincontrol/index' => "admincontrol#index"
  get 'admincontrol/zizuminfo' => "admincontrol#zizuminfo"
  get 'admincontrol/menu' => "admincontrol#menu"
  get 'admincontrol/restaurant' => "admincontrol#restaurant"
  get 'admincontrol/zizumupdate' => "admincontrol#zizumupdate"
  get 'admincontrol/resupdate' => "admincontrol#resupdate"
  get 'admincontrol/menuupdate' => "admincontrol#menuupdate"
  #===============메뉴별 제보 요청==============
 get 'userrequests/index'

 get 'userrequests/new'

 get 'userrequests/ask'

 get 'edit_asks/index'
 
 get 'edit_asks/ask'
  ## 수정 / 삭제 요청 ###
  #요청 확인
  get '/userrequests' => 'userrequests#index'
  #메뉴 추가 요청
  get '/userrequests/new_request' => 'userrequests#new_request'
  post '/userrequests/create' => 'userrequests#create'
  #메뉴 수청 / 삭제 요청
  get '/userrequests/edit_request' => 'userrequests#edit_request'
  post '/userrequests/edit_request' => 'userrequests#edit_request'
  #승인
  post '/userrequests/permit' => 'userrequests#permit'
  #=================================
  
  # 나만의 페이지
  resources :profiles
  # post '/profiles/:id/myposts' => 'profiles#myposts'
  scope 'profiles/:id' do
    get 'myposts', :to => 'profiles#myposts'
    get 'mycomments', :to => 'profiles#mycomments'
    get 'myrequests', :to => 'profiles#myrequests'    
  end
  get '/zizuminfos/:id/follow_destroy', to: 'follows#profile_follow_destroy_toggle', as: 'profile_follow_destroy'

  # # Follow 기능
  # post '/zizuminfos/:id/follow', to: 'follows#zizum_back_follow_toggle', as: 'zizum_back_follow'
  # post '/menus/index/params', to: 'follows#zizum_front_follow_toggle', as: 'zizum_front_follow'

  # freeboards 용
    post "/checkNum" => "freeboards#checkNum"

    # get '/freeboards/'
  resources :recipes
  resources :freeboards
  resources :userrequests
  resources :zizuminfos
  resources :restaurants
  resources :menus

  get 'home/index'
  root 'home#index'

  #============크롤링===============
  get '/crawling' => 'restaurants#crawling'
  #================================
  post '/tinymce_assets' => 'tinymce_assets#create'
  # user
  # post '/users/checkDouble' => 'user/registrations#checkDouble'
  # post "/users/checkDouble" => "user/registrations#checkDouble" 
  devise_scope :user do
     post "/users/checkDouble" => "user/registrations#checkDouble" 
     post "/checkDouble" => "user/registrations#checkDouble"
     get "/users" => 'user/registrations#new'
  end
  devise_for :users, :controllers => {registrations: 'user/registrations',passwords: 'users/passwords' }
  # devise_scope :user do
  #   get 'editsns', :to => 'devise/registrations#editsns'
  # end
  # resources :comments, only: [:create, :destroy]
  resources :comments do
    member do
      put "like", to: "comments#like"
      put "unvote", to: "comments#unvote" 
      put "dislike", to: "comments#dislike"    
    end    
  end


  # 알림
  # get '/new_alarms/read_all' => 'new_alarms#read_all'
  # resources :new_alarms #순서이대로
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'# 맨아래에 둬주세요
  
  # concern :paginatable do
  #   get '(page/:page)', action: :index, on: :collection, as: ''
  # end
  
  # resources :my_resources, concerns: :paginatable
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_nested_set :scope => [:commentable_id, :commentable_type]
  acts_as_votable

  validates :body, :presence => true
  validates :user, :presence => true

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_votable

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def image(writer)
    if writer.profileimg.url == nil
      writer.profileimg = 'defaultImg3.jpg'  
    else
      writer.profileimg.url
    end
  end
  
  def self.build_from(obj, user_id, comment)
    new \
      :commentable => obj,
      :body        => comment,
      :user_id     => user_id
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.any?
  end

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
   
    def create
      commentable = commentable_type.constantize.find(commentable_id)
      @comment = Comment.build_from(commentable, current_user.id, body)
      @comment.user = current_user
      @category = commentable_type.constantize.find(commentable_id).category
      @post = Freeboard.find(commentable_id)
      
      respond_to do |format|
        if @comment.save
            make_child_comment
            format.html  { redirect_to("#{request.referrer}#comment#{@comment.id}", :notice => '댓글이 작성되었습니다.') }
                # 댓글에 대댓글 작성 시 댓글 작성자에게 알림이 울림.
                # if @comment.parent != nil && @comment.parent.user != current_user
                #     @new_alarm = NewAlarm.create! user:  @comment.parent.user,
                #                                   # content: "#{current_user.name.truncate(15, omission: '...')} 님이 답댓글을 달았습니다.",
                #                                   # content: "",
                #                                   link: request.referrer
                                                  
                  
                # end  
        else

            format.html  { redirect_to(request.referrer, :alert => '댓글 내용을 작성해주세요.') }
        end
      end
    end

## 수정해야할부분 내작성글에 댓글달았을 때 거기에 답글다는경우(작성글댓글로알림)/내작성글에 a유저의 댓글에 b유저가 답글다는경우(나에게는 작성글댓글, a유저에겐 답글알림)
    #   if @comment.parent == nil && commentable.user != current_user 
    #     # puts "테스트 #{NewAlarm.where(link: freeboard_path(:id=>commentable)).count}끝"
    #     @alarms = NewAlarm.where(link: freeboard_path(:id=>commentable))
    #     if @alarms.count != 0
    #       @alarms[0].mark_as_read! for: commentable.user
    #       @new_alarm = NewAlarm.create! user: commentable.user,
    #                                       content: "#{Comment.where(commentable: commentable).count}",
    #                                       link: URI(request.referer).path
    #     else 
    #       @new_alarm = NewAlarm.create! user: commentable.user,
    #                                     content: "#{Comment.where(commentable: commentable).count}",
    #                                     link: URI(request.referer).path
    #     end  
    #   end                             
    # end

    def destroy
        @comment = Comment.find_by(id: params[:id])
        @comment.delete
        respond_to do |format|
          format.html { redirect_to(request.referrer, :notice => '댓글이 삭제되었습니다.')}
          format.js
        end
    end

  #추천기능
  def like
    @comment = Comment.find_by(id: params[:id])
    @comment.liked_by(current_user)
    redirect_back fallback_location: root_path
  end  
      
  def unvote
    @comment = Comment.find_by(id: params[:id])
    @comment.unvote_by(current_user)
    redirect_back fallback_location: root_path           
    # respond_to do |format|
    #   format.js {
    #     render "comments/votes"
    #   }
    # end
  end

  def dislike
    @comment = Comment.find_by(id: params[:id])
    @comment.dislike_by(current_user)
    redirect_back fallback_location: root_path           
    # respond_to do |format|
    #   format.js {
    #     render "comments/votes"
    #   }
    # end
  end
   
    private
    def comment_params
      params[:comment][:user_id] = current_user.id
      params.require(:comment).permit(:body, :commentable_id, :commentable_type, :comment_id, :post, :user_id, :name)
    end
   
    def post
      Freeboard.find(commentable_id)
    end

    def commentable_type
      comment_params[:commentable_type]
    end
   
    def commentable_id
      comment_params[:commentable_id]
    end
   
    def comment_id
      comment_params[:comment_id]
    end
   
    def body
      comment_params[:body]
    end
   
    def make_child_comment
      return "" if comment_id.blank?
   
      parent_comment = Comment.find comment_id
      @comment.move_to_child_of(parent_comment)
    end
  
  end

app/views/comments/_answer.html.erb
<% comments.each do |comment| %>  
  <div class="comments-show nago">
    <div class="comment comment-bar">

      <div class="comment-profile form-inline"> <!--프로필-->
        <%=link_to(image_tag(comment.image(comment.user),class:"post-profile-img"), profile_path(comment.user.profile.id)) %>

        <% if comment.user ==nil %><i>탈퇴한 회원입니다</i><%else%>
        <%= link_to comment.user.name, profile_path(comment.user.profile.id) ,class:"linkto"%><%end%>
        <div style="font-size:0.8rem; color: rgb(140,140,140); font-weight:lighter;margin-left:1rem;"> <%= time_ago_in_words(comment.created_at) %>전 [ <%= comment.created_at.strftime('%Y-%m-%d %H:%M') %> ] </div> 
        <% if current_user == comment.user %>
          &nbsp;/&nbsp;<%= link_to "삭제", comment_path(comment), method: :delete, remote: false, data: { confirm: "정말로 지우시겠습니까?" }, style: "font-size:0.8rem; color: rgb(140,140,140);" %>
        <% end %>  

          <!--추천기능 only in 질문글-->
        <div class="comment-vote" style="text-align:center;margin-top:0.5rem;margin-left:auto;margin-right:1rem;">
          <% if current_user %>    
            <span style="font-weight: bold; font-size:0.8rem; color: rgb(120,120,120);">추천수: <%= comment.weighted_score%></span> &nbsp;             
            <% if current_user.liked? (comment) %>
              <%= link_to raw("<i class=\"fas fa-thumbs-up\"></i>"), unvote_comment_path(comment), method: :put,class:"vote-btn" %> <% else %>
              <%= link_to raw("<i class=\"far fa-thumbs-up\"></i>"), like_comment_path(comment), method: :put,class:"vote-btn" %>
            <% end %> &nbsp;
            <% if current_user.disliked? (comment) %>
              <%= link_to raw("<i class=\"fas fa-thumbs-down\"></i>"), unvote_comment_path(comment), method: :put,class:"vote-btn"  %><% else %>
              <%= link_to raw("<i class=\"far fa-thumbs-down\"></i>"), dislike_comment_path(comment), method: :put,class:"vote-btn"  %> 
            <% end %>
          
          <% else %>
              <a class="disabled vote-btn"style="cursor:pointer;"><i class=\"far fa-thumbs-up\"></i> </a><br>
              <%= comment.weighted_score%><br>      
              <a class="disabled vote-btn"style="cursor:pointer;"><i class=\"far fa-thumbs-down\"></i></a>
          <% end %>
        </div>

      </div>

      <div class="comment-content" style="margin:0.6rem 0rem 0rem 0.4rem;">  <!--댓글내용-->
        <div style="display:flex;">
        
        

          <%= content_tag(:div, comment.body, style:"white-space: pre-wrap;margin:1rem 3rem 0rem 3rem;align-items:center;") %>

        </div>  
      <% if user_signed_in? && current_user.name != nil %> <!--답글창-->
      <%# <div class="comment-nav" > %>

        <button onclick="showHide('comment_<%= comment.id %>')" onfocus="this.blur()" class="reply-btn">답글</button>

      </div>

      <div id="comment_<%= comment.id %>" style="display:none;margin:0.3rem;"> 
        <div class="reply-form">
          <%= form_for @new_comment do |f| %>
            <%= f.hidden_field :commentable_id, value: @new_comment.commentable_id %>
            <%= f.hidden_field :commentable_type, value: @new_comment.commentable_type %>
            <%= f.hidden_field :comment_id, value: comment.id %>
            <div class="field form-group">
              <%= f.hidden_field :name, value: current_user.name, required: "true" %>
              <%= f.text_area :body, class: 'form-control' %>
              <%= submit_tag "답댓글 작성", class:"reply-btn rereply-btn", style:"float:right;" %>
            </div>
            
          <% end %>
        </div>
      </div>
      <%end%>  <!--//답글창-->
      <br/>
     
    </div> <!--//comment-->
    <%# <div style="margin-left: 20px;"> %>
    <div>    
      <%= render partial: "comments/reply_end", locals: {comments: comment.children} %>
    </div>

  </div>

  
<% end %>

app/views/comments/_form.html.erb
<% if user_signed_in? && current_user.name != nil &&  @new_comment.commentable.category != "제보글"%>
  <%= form_for @new_comment do |f| %>  
    <%= f.hidden_field :commentable_id, value: @new_comment.commentable_id %>
    <%= f.hidden_field :commentable_type, value: @new_comment.commentable_type %>
    <div class="field form-group form-inline">
      <%= f.text_area :body, class: 'comment form-control',placeholder:"주제와 무관한 댓글, 악플은 삭제될 수 있습니다." %>
    <%# </div>
    
    <div class="field form-group"> %>
      <%= submit_tag "등록", class:"comment-btn" %><br/>
    </div>
  <% end %>

<% elsif  user_signed_in? && current_user.admin? &&@new_comment.commentable.category == "제보글" %>
  <%= form_for @new_comment do |f| %>  
    <%= f.hidden_field :commentable_id, value: @new_comment.commentable_id %>
    <%= f.hidden_field :commentable_type, value: @new_comment.commentable_type %>
    <%# <%= form_for @new_comment.commentable do |p| %>     
    <div class="field form-group form-inline">
      <%= f.text_area :body, class: 'comment form-control',placeholder:"관리자용" %>    
      <%= submit_tag "등록", class:"comment-btn" %><br/>
    </div>
  <% end %>
<% elsif user_signed_in? && !current_user.admin? && @new_comment.commentable.category == "제보글"%>
  <div class="field form-group">
    <%= text_area_tag :nil, "", class: "form-control", placeholder: "관리자용 댓글창입니다." %>
  </div>
<% else %>
  <div class="field form-group">
    <%= text_area_tag :nil, "", class: "form-control", placeholder: "회원가입 후 이용가능합니다." %>
  </div>
<% end %>

app/views/comments/_reply.html.erb
<% comments.each do |comment| %>  
  <div class="comments-show nago">
    <div class="comment comment-bar">
      <div class="comment-profile form-inline"> <!--프로필-->
        <%=link_to(image_tag(comment.image(comment.user),class:"post-profile-img"), profile_path(comment.user.profile.id)) %>
        
        <% if comment.user ==nil %><i>탈퇴한 회원입니다</i><%else%>
        <%= link_to comment.user.name, profile_path(comment.user.profile.id) ,class:"linkto"%><%end%>
        <%# <%= link_to comment.user.name, profile_path(comment.user.profile.id),class:"linkto" %> 
        <div style="font-size:0.8rem; color: rgb(140,140,140); font-weight:lighter;margin-left:1rem;"> <%= time_ago_in_words(comment.created_at) %>전 [ <%= comment.created_at.strftime('%Y-%m-%d %H:%M') %> ] </div> 
        <% if current_user == comment.user %>
          &nbsp;/&nbsp;<%= link_to "삭제", comment_path(comment), method: :delete, remote: false, data: { confirm: "정말로 지우시겠습니까?" }, style: "font-size:0.8rem; color: rgb(140,140,140);" %>
        <% end %>  
      </div>

      <div class="comment-content" style="margin:0.6rem 0rem 0rem 0.4rem;">  <!--댓글내용-->
        <%= content_tag(:div, comment.body, style: "white-space: pre-wrap;") %>
      <% if user_signed_in? && current_user.name != nil %> <!--답글창-->
      <%# <div class="comment-nav" > %>
        <button onclick="showHide('comment_<%= comment.id %>')" onfocus="this.blur()" class="reply-btn">답글</button>
      </div>

      <div id="comment_<%= comment.id %>" style="display:none;margin:0.3rem;"> 
        <div class="reply-form">
          <%= form_for @new_comment do |f| %>
            <%= f.hidden_field :commentable_id, value: @new_comment.commentable_id %>
            <%= f.hidden_field :commentable_type, value: @new_comment.commentable_type %>
            <%= f.hidden_field :comment_id, value: comment.id %>
            <div class="field form-group">
              <%= f.hidden_field :name, value: current_user.name, required: "true" %>
              <%= f.text_area :body, class: 'form-control' %>
               <%= submit_tag "답댓글 작성", class:"reply-btn rereply-btn", style:"float:right;" %>
            </div>
            
          <% end %>
        </div>
      </div>
      <%end%>  <!--//답글창-->
      <br/> 

    </div> <!--//comment-->
    <%# <div style="margin-left: 20px;"> %>
    <div>    
      <%= render partial: "comments/reply_end", locals: {comments: comment.children} %>
    </div>

  </div>

  
<% end %>

app/views/comments/_reply_end.html.erb

<% comments.each do |comment| %>  
  <div class="comments-show nago">
    <div class="comment reply-box">
      <div class="comment-profile form-inline"> <!--프로필-->
        <i class="fas fa-level-up-alt"></i>        
        <%# <%=image_tag("beige-logo.PNG", class:"comment-profile-img")%>
        <% if comment.user ==nil %>
          <i>탈퇴한 회원입니다</i>
        <%else%>
          <%= link_to comment.user.name, profile_path(comment.user.profile.id),class:"linkto nago", style:"font-weight: 500; font-size: 1rem; margin-left: 0.5rem;" %> 
        <%end%>
        <div style="font-weight:lighter;margin-left:1rem; font-size:0.8rem; color: rgb(140,140,140); "> <%= time_ago_in_words(comment.created_at) %>전 [ <%= comment.created_at.strftime('%Y-%m-%d %H:%M') %> ] </div> 
        <% if current_user == comment.user %>
          &nbsp;/&nbsp;<%= link_to "삭제", comment_path(comment), method: :delete, remote: false, data: { confirm: "정말로 지우시겠습니까?" }, style: "font-size:0.8rem; color: rgb(140,140,140);" %>
        <% end %>  
      </div>

      <div class="comment-content " style="margin:0rem 0rem 1.6rem 2.5rem;">  <!--답글내용-->
        <div class="d-flex">
          <p style ="color: #4b5d79;font-size: 0.8rem;margin-top: 0.2rem;margin-left: 0.5rem;">@<%= comment.parent.user.name %></p>
          <%= content_tag(:div, comment.body, style: "white-space: pre-wrap;margin-left:0.8rem;") %>
        </div>
      <% if user_signed_in? && current_user.name != nil %> <!--답글창-->
        <button onclick="showHide('comment_<%= comment.id %>')" onfocus="this.blur()" class="reply-end-btn">답글</button>
      </div>
    
      <div id="comment_<%= comment.id %>" style="display:none;margin:0.3rem;"> 
        <div class="reply-form">
          <%= form_for @new_comment do |f| %>
            <%= f.hidden_field :commentable_id, value: @new_comment.commentable_id %>
            <%= f.hidden_field :commentable_type, value: @new_comment.commentable_type %>
            <%= f.hidden_field :comment_id, value: comment.id %>
            <div class="field form-group">
              <%= f.hidden_field :name, value: current_user.name, required: "true" %>
              <%= f.text_area :body, class: 'form-control' %>
               <%= submit_tag "답댓글 작성", class:"reply-btn rereply-btn", style:"float:right;" %>
            </div>
             
          <% end %>
        </div>
      </div>
      <%end%>  <!--//답글창-->
    </div> <!--//comment-->
    <div>
      <%= render partial: "comments/reply_end", locals: {comments: comment.children} %>
    </div>

  </div>
<% end %>


app/views/comments/_template.html.erb
<%# <div class="comments-header">  
        <h4>답변 (<%= commentable.comment_threads.count %>

 
<div class="comments-container">  
    <% if @freeboard.category == "질문글" %>
        <%= render partial: "comments/answer",  locals: {comments: commentable.root_comments} %>
    <% else %>    
        <%= render partial: "comments/reply",  locals: {comments: commentable.root_comments} %>
    <% end %>
</div>