config/routes.rb
Rails.application.routes.draw do

  resources :notices

  resources :conversations do
    resources :messages
  end

  get 'conversations/admin' => 'conversations#admin'

  get 'legal/privacy' => "legal#privacy"
  get 'legal/using' => "legal#using"
  #PROFILE------FOLLOW/UNFOLLOW
  get 'profiles/:id/follow' => 'follows#profile_follow', as: 'profile_follow'

  ##SEARCH------resources :zizuminfos 보다 위에
  get 'zizuminfos/search/' => "zizuminfos#search"
  post 'zizuminfos/getZizum' => "zizuminfos#getZizum"
  get 'zizuminfos/getGungu' => "menus#getGungu"
  get 'zizuminfos/zizummenus' => "zizuminfos#zizummenus"
  get 'zizuminfos/:id/show' => "zizuminfos#show"
  #밑에 꺼 꼭 넣어야함.
  get 'zizuminfos/index' => "zizuminfos#index", as: 'zizuminfos'
  ##-------------------------------------


  #SEARCH----------resouces :menus 보다 위에 가게 해야 함! --------------------
  get 'restaurants/search' => "restaurants#search"
  get 'menus/search/' => "menus#search"
  get 'menus/getGungu' => "menus#getGungu"
  get 'menus/menus/getGungu' => "menus#getGungu"
  get 'zizuminfos/getGungu' => "menus#getGungu"
  #밑에 꺼 꼭 넣어야함.
  get 'menus/index' => "menus#index", as: 'menus'
  #--------------------------------------------------------------------------

  #-----------------좋아요 ajax
  get 'follows/zizumfollow' => "follows#zizumfollow"
  get 'follows/recipefollow' => "follows#recipefollow"
  
  #-----------admin 관리 페이지
  get 'admincontrol/index' => "admincontrol#index"
  get 'admincontrol/zizuminfo' => "admincontrol#zizuminfo"
  get 'admincontrol/menu' => "admincontrol#menu"
  get 'admincontrol/restaurant' => "admincontrol#restaurant"
  get 'admincontrol/zizumupdate' => "admincontrol#zizumupdate"
  get 'admincontrol/resupdate' => "admincontrol#resupdate"
  get 'admincontrol/menuupdate' => "admincontrol#menuupdate"
  #===============메뉴별 제보 요청==============
 get 'userrequests/index'

 get 'userrequests/new'

 get 'userrequests/ask'

 get 'edit_asks/index'
 
 get 'edit_asks/ask'
  ## 수정 / 삭제 요청 ###
  #요청 확인
  get '/userrequests' => 'userrequests#index'
  #메뉴 추가 요청
  get '/userrequests/new_request' => 'userrequests#new_request'
  post '/userrequests/create' => 'userrequests#create'
  #메뉴 수청 / 삭제 요청
  get '/userrequests/edit_request' => 'userrequests#edit_request'
  post '/userrequests/edit_request' => 'userrequests#edit_request'
  #승인
  post '/userrequests/permit' => 'userrequests#permit'
  #=================================
  
  # 나만의 페이지
  resources :profiles
  # post '/profiles/:id/myposts' => 'profiles#myposts'
  scope 'profiles/:id' do
    get 'myposts', :to => 'profiles#myposts'
    get 'mycomments', :to => 'profiles#mycomments'
    get 'myrequests', :to => 'profiles#myrequests'    
  end
  get '/zizuminfos/:id/follow_destroy', to: 'follows#profile_follow_destroy_toggle', as: 'profile_follow_destroy'

  # # Follow 기능
  # post '/zizuminfos/:id/follow', to: 'follows#zizum_back_follow_toggle', as: 'zizum_back_follow'
  # post '/menus/index/params', to: 'follows#zizum_front_follow_toggle', as: 'zizum_front_follow'

  # freeboards 용
    post "/checkNum" => "freeboards#checkNum"

    # get '/freeboards/'
  resources :recipes
  resources :freeboards
  resources :userrequests
  resources :zizuminfos
  resources :restaurants
  resources :menus

  get 'home/index'
  root 'home#index'

  #============크롤링===============
  get '/crawling' => 'restaurants#crawling'
  #================================
  post '/tinymce_assets' => 'tinymce_assets#create'
  # user
  # post '/users/checkDouble' => 'user/registrations#checkDouble'
  # post "/users/checkDouble" => "user/registrations#checkDouble" 
  devise_scope :user do
     post "/users/checkDouble" => "user/registrations#checkDouble" 
     post "/checkDouble" => "user/registrations#checkDouble"
     get "/users" => 'user/registrations#new'
  end
  devise_for :users, :controllers => {registrations: 'user/registrations',passwords: 'users/passwords' }
  # devise_scope :user do
  #   get 'editsns', :to => 'devise/registrations#editsns'
  # end
  # resources :comments, only: [:create, :destroy]
  resources :comments do
    member do
      put "like", to: "comments#like"
      put "unvote", to: "comments#unvote" 
      put "dislike", to: "comments#dislike"    
    end    
  end


  # 알림
  # get '/new_alarms/read_all' => 'new_alarms#read_all'
  # resources :new_alarms #순서이대로
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'# 맨아래에 둬주세요
  
  # concern :paginatable do
  #   get '(page/:page)', action: :index, on: :collection, as: ''
  # end
  
  # resources :my_resources, concerns: :paginatable
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user
    acts_as_commentable
    is_impressionable

    acts_as_followable

    mount_uploader :recipeimage0, S3Uploader
    mount_uploader :recipeimage1, S3Uploader
    mount_uploader :recipeimage2, S3Uploader
    mount_uploader :recipeimage3, S3Uploader
    mount_uploader :recipeimage4, S3Uploader
    mount_uploader :recipeimage5, S3Uploader
    mount_uploader :recipeimage6, S3Uploader
    mount_uploader :recipeimage7, S3Uploader
    mount_uploader :recipeimage8, S3Uploader
    mount_uploader :recipeimage9, S3Uploader
    mount_uploader :recipeimage10, S3Uploader


    def self.search(key)
        # for i in 1..10
        where("allergyfor || title|| explain LIKE ?", "%#{key}%")    
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  impressionist actions: [:show]
  # GET /recipes
  # GET /recipes.json
  def index

    @recipe_key = params[:recipe_word]
    @allergy_tags=["난류", "우유", "복숭아", "토마토", "메밀", "밀", "대두(콩)", "닭고기", "쇠고기", "돼지고기", "새우", "고등어", "홍합", "전복", "굴", "조개류", "게", "오징어", "호두", "땅콩", "아황산류"]

    recipes = if params[:recipe_word]
      if params[:recipe_word] == ""
        @recipes = Kaminari.paginate_array(Recipe.all.order("created_at DESC")).page(params[:page]).per(9)
        return
      end
      key_del = @recipe_key.delete"#"
      @recipe_keys = key_del.split(' ')
      count = @recipe_keys.length()
      for idx in 0...count
        key = "%#{@recipe_keys[idx]}%"
        
        recipe = Recipe.where("title  LIKE (?) || explanation LIKE (?) || allergyfor LIKE (?) ", key, key, key).order("created_at DESC")
        if idx == 0
          @recipes = recipe
        else
          @recipes = @recipes & recipe
        end
      end
      @recipes = Kaminari.paginate_array(@recipes.uniq).page(params[:page]).per(9)
    else
      @recipes = Kaminari.paginate_array(Recipe.all.order("created_at DESC")).page(params[:page]).per(9)
    end
    
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @ingredients = @recipe.ingredients
    @ingredients = @ingredients.split("\n")
    puts @ingredients
  end

  # GET /recipes/new
  def new
    if user_signed_in? && current_user.name == nil
      flash[:warning] ='닉네임을 설정해주세요'
      redirect_to edit_user_registration_path
    end
    @recipe = Recipe.new
    @allergy_tags=["난류", "우유", "복숭아", "토마토", "메밀", "밀", "대두(콩)", "닭고기", "쇠고기", "돼지고기", "새우", "고등어", "홍합", "전복", "굴", "조개류", "게", "오징어", "호두", "땅콩", "아황산류"]
  end

  # GET /recipes/1/edit
  def edit
    @allergy_tags=["난류", "우유", "복숭아", "토마토", "메밀", "밀", "대두(콩)", "닭고기", "쇠고기", "돼지고기", "새우", "고등어", "홍합", "전복", "굴", "조개류", "게", "오징어", "호두", "땅콩", "아황산류"]
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    @recipe.name = current_user.name
    @recipe.category = "레시피"

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:allergyfor, :recipeimage0, :title, :explanation, :ingredients, :tag, :content1, :content2, :content3, :content4, :content5, :content6, :content7, :content8, :content9, :content10,
         :recipeimage1, :recipeimage2, :recipeimage3, :recipeimage4, :recipeimage5, :recipeimage6, :recipeimage7, :recipeimage8, :recipeimage9, :recipeimage10)
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_bookmarkModal.html.erb
<!-- Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
<div class="modal-dialog recipe-modal-dialog" role="document">
    <div class="modal-content recipe-modal-content">
    <div class="modal-header">
        <div class="modal-title" id="exampleModalLabel">북마크한 사용자&nbsp;<%=@recipe.followers_count%>명</div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body recipe-modal-body">
        
       
        <%@recipe.followers.each do |follower|%>
            <%=link_to profile_path(follower.profile.id) do%>
            <div class="recipe-about-follower d-flex">
                <div class="recipe-about-writer-imgbox">
                    <% if follower.profileimg.url != nil%>
                        <%=image_tag follower.profileimg.url%>
                    <%elsif%>
                        <%= image_tag "beige-logo.PNG"%>
                    <%end%>
                </div>

                <div class="recipe-about-writer linkto">
                    <%= follower.name%>
                </div>
                </div>
            <%end%>
        <%end%>
    </div>
    </div>
</div>
</div>


app/views/recipes/_form.html.erb
<%= form_for(recipe) do |f| %>
  <div class="recipe-new-upper d-flex justify-content-between">
    <div class="recipe-new-upper-main">레시피 등록</div>
    <div class="recipe-new-upper-submit">
      <%= f.submit "공유하기",  class: "post-submit-button" %>
    </div>
  </div>
  
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="recipe-new-intro row">
    <div class="col-4">
      <div class="recipe-new-body-imgcap">
        <div>레시피 대표 사진 등록</div>
        <%= image_tag("defaultImg3.jpg", class: "recipe-new-representative", id: "firstImg imgPlace") %>
        <div class="target"></div>
      </div> 

      <div class="field">
        <%= f.file_field :recipeimage0, type: "file", class: "pictureInput", accept: 'image/png,image/gif,image/jpeg', style: "margin-right: 100px; margin-top: 5px; margin-bottom: 5px" %> 
      </div>
    </div>

    <div class="recipe-new-intro-text col-8">
      <div class="field recipe-new-intro-field d-flex">
        <%= f.label :title, "레시피 제목" , class: "recipe-new-form-title"%>
        <%= f.text_field :allergyfor, class: "recipe-new-intro-allergyfor", placeholder:"ex)밀, 우유"%> 알레르기 보유자를 위한 
        <%= f.text_field :title, class: "recipe-new-intro-input recipe-new-intro-title", placeholder:"ex)호두식빵 레시피"%>
      </div>

      <div class="field recipe-new-intro-field d-flex">
        <%= f.label :explanation, "레시피 한 줄 설명", class: "recipe-new-form-title"%>
        <%= f.text_field :explanation, class: "recipe-new-intro-input"%>
      </div>

      <div class="field recipe-new-intro-field d-flex">
        <%= f.label :ingredients, "레시피 재료", class: "recipe-new-form-title"%>
        <%= f.text_area :ingredients, class: "recipe-new-intro-input-ingr"%>
      </div>


    </div>
  </div>
  

  <%# 되도록이면 div 위계 지킬 것. 밑에 스크립트 부모자식관계 변형됨 %>
  <div class="divide-line recipe-new-divide-line"></div>
  <div class="recipe-new-body">
    <div class="recipe-new-body-element">
      <div class="recipe-new-body-imgcap d-flex">     
        <%= image_tag("defaultImg3.jpg", class: "recipe-new-defaultimg", id: "firstImg imgPlace") %>
        <div class="target"></div>
        
        <div class="field flex-grow-1">
          <%= f.text_area :content1, class:"recipe-new-body-cap", placeholder: "레시피의 각 단계에 대한 설명을 작성해주세요" %>
        </div>
      </div>

      <div class="field">
        <%= f.file_field :recipeimage1, type: "file", class: "pictureInput", accept: 'image/png,image/gif,image/jpeg', style: "margin-right: 100px; margin-top: 5px; margin-bottom: 5px" %> 
      </div>
    </div>
    
    <% for x in 2..10 %>

      <div id="hiddenList<%=x%>">
        <br>
        <div class="recipe-new-body-element">
          <div class="recipe-new-body-imgcap d-flex">     
            <%= image_tag("defaultImg3.jpg", class: "recipe-new-defaultimg", id: "firstImg imgPlace") %>
            <div class="target"></div>
            
            <div class="field flex-grow-1">
              <%= f.text_area :"content#{x}", class:"recipe-new-body-cap", placeholder: "레시피의 각 단계에 대한 설명을 작성해주세요" %>
            </div>
          </div>

          <div class="field">
            <%= f.file_field :"recipeimage#{x}", type: "file", class: "pictureInput", accept: 'image/png,image/gif,image/jpeg', style: "margin-right: 100px; margin-top: 5px; margin-bottom: 5px" %> 
           
          </div>
        </div>
      </div>
      
      
    <% end %>
 
      <div id= "addBtn" class="recipe-new-body-add">
        <i class="fas fa-plus"></i>
      </div>

      <div class="recipe-new-representative">
        
      </div>

      <div class="actions">
        <%= f.submit "공유하기", class: "post-submit-button"%>
      </div>

  <% end %>

</div>

<script>
  var tagadd = ''
  var tagarray = [];

  $(".allergy-tag").click(function(){
    if($(this).hasClass("allergy-tag-selected")){
      $(this).removeClass("allergy-tag-selected");
      $("#tag-"+$(this).html()).remove();
      tagadd = $(".allergy-tag-showlist").html();
      tagarray.splice(tagarray.indexOf($(this).html()),1);
    }
    else{
      $(this).addClass("allergy-tag-selected");
      tagadd += '<div class="allergy-tag-name" id="'+"tag-"+$(this).html()+'">' + $(this).html() +'</div>';
      $(".allergy-tag-showlist").html(tagadd);
      tagarray.push($(this).html());
    }

    $(".allergy-tag-input").val(tagarray);
  })



  $(document).ready(function(){
    $("#addBtn").click(function(){
        if($("#hiddenList2").is(":hidden")){
          // $("#spreadBtn1").toggleClass("fas fa-arrow-alt-circle-right fas fa-arrow-alt-circle-down");
          $("#hiddenList2").slideDown();
        }else if($("#hiddenList3").is(":hidden")){
          $("#hiddenList3").slideDown();
        }else if($("#hiddenList4").is(":hidden")){
          $("#hiddenList4").slideDown();
        }else if($("#hiddenList5").is(":hidden")){
          $("#hiddenList5").slideDown();
        }else if($("#hiddenList6").is(":hidden")){
          $("#hiddenList6").slideDown();
        }else if($("#hiddenList7").is(":hidden")){
          $("#hiddenList7").slideDown();
        }else if($("#hiddenList8").is(":hidden")){
          $("#hiddenList8").slideDown();
        }else if($("#hiddenList9").is(":hidden")){
          $("#hiddenList9").slideDown();
        }else if($("#hiddenList10").is(":hidden")){
          $("#hiddenList10").slideDown();
        }
    });

    $("#deleteBtn2").click(function(){
      if($("#hiddenList2").is(":visible")){
        $("#hiddenList2").slideUp();
        $(this).siblings('input').val('');
      }
    });
    $("#deleteBtn3").click(function(){
      if($("#hiddenList3").is(":visible")){
        $("#hiddenList3").slideUp();
        $(this).siblings('input').val("");
      }
    });
    $("#deleteBtn4").click(function(){
      if($("#hiddenList4").is(":visible")){
        $("#hiddenList4").slideUp();
        $(this).siblings('input').val("");
      }
    });
    $("#deleteBtn5").click(function(){
      if($("#hiddenList5").is(":visible")){
        $("#hiddenList5").slideUp();
        $(this).siblings('input').val("");
      }
    });
    $("#deleteBtn6").click(function(){
      if($("#hiddenList6").is(":visible")){
        $("#hiddenList6").slideUp();
        $(this).siblings('input').attr("class");
        $(this).siblings('input').val("");
      }
    });
    $("#deleteBtn7").click(function(){
      if($("#hiddenList7").is(":visible")){
        $("#hiddenList7").slideUp();
        $(this).siblings('input').attr("class");
        $(this).siblings('input').val("");
      }
    });
    $("#deleteBtn8").click(function(){
      if($("#hiddenList8").is(":visible")){
        $("#hiddenList8").slideUp();
        $(this).siblings('input').attr("class");
        $(this).siblings('input').val("");
      }
    });
    $("#deleteBtn9").click(function(){
      if($("#hiddenList9").is(":visible")){
        $("#hiddenList9").slideUp();
        $(this).siblings('input').attr("class");
        $(this).siblings('input').val("");
      }
    });
    $("#deleteBtn10").click(function(){
      if($("#hiddenList10").is(":visible")){
        $("#hiddenList10").slideUp();
        $(this).siblings('input').attr("class");
        $(this).siblings('input').val("");
      }
    });
  });

  $(".recipe-new-defaultimg, .recipe-new-representative").click(function(){
    $(this).parent().siblings('div.field').children('input').trigger('click');
  })


$(function() {
  $('input.pictureInput').on('change', function(event) {
    var files = event.target.files;
    console.log(files);
    var image = files[0];
    // here's the file size
    console.log(image.size);

    $tempImg = $(this).parent().siblings().children('img');
    
    var reader = new FileReader();
    reader.onload = function(file) {
      var img = new Image();
      console.log(file);
      $tempImg.attr('src',file.target.result);
      // img.width = 500;
      // img.height = 400;

      // $tempImg.css('display','none');        
      // $tempTarget.html(img);
      // $(this).parent().siblings('div#recipeField').children('img#imgPlace').css('display', 'none');
      // $(this).parent().siblings('div#recipeField').children('div#target').html(img);
    }
    reader.readAsDataURL(image);
    console.log(files);
  });
});

</script>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<div class="banner-image-box">
    <%=image_tag("recipe-top.png", class:"banner-image")%>
</div>

<div class="recipe-index-upper">
  <div class="recipe-index-upper-container container">
    <%= form_tag(recipes_path, method: :get) do %>
      <div class="recipe-index-search-area">
        <div class="recipe-index-search-box">
          <%= text_field_tag :recipe_word, params[:recipe_word], class: "recipe-index-search-input", placeholder: "검색어 입력(띄어쓰기로 구분해주세요)"%>   
          <button type="submit" class="recipe-index-search-btn">검색하기</button>
        </div>
      </div>

      <div class="recipe-index-search-area2">
        <div class="recipe-index-search-tagbox">
          <% @allergy_tags.each do |tag|%>
            <div class="recipe-index-search-tag">#&nbsp;<%=tag%></div>
          <%end%>
        </div>
      </div>
    <%end%>
  </div>
</div>

<div class="recipe-index-main container">
  <div class="recipe-index-main-count">총 <%=@recipes.total_count%>건</div>
  <div class="recipe-index-body row">
    <% @recipes.each do |recipe|%>
      <div class="recipe-index-outbox col-4">
        <div class="recipe-index-box">
          <%=link_to recipe do%>
            <div class="recipe-index-imgbox">
              <% if recipe.recipeimage0.blank?%>
                <%=image_tag("beige-logo.PNG",class:"recipe-index-img")%>
              <%else%>
                <%=image_tag recipe.recipeimage0.url, class:"recipe-index-img"%>
              <%end %>
            </div>
          <%end%>
          <div class="d-flex justify-content-end recipe-index-bookmark-area">
            <%if user_signed_in?%>
                <% if recipe.followed_by?(current_user) %>
                    <!-- 좋아요를 했다면 -->
                    <i class="fas fa-bookmark recipe-index-bookmark"></i>
                    <div class="recipe-index-id-bookmark"><%= recipe.id%></div>
                <% else %>
                    <!-- 좋아요를 안 했다면 -->
                    <i class="far fa-bookmark recipe-index-bookmark recipe-index-nobookmark"></i>
                    <div class="recipe-index-id-bookmark"><%= recipe.id%></div>
                <% end %>
            <%else%>
            <i class="far fa-bookmark recipe-index-bookmark recipe-index-nobookmark" data-toggle="modal" data-target="#loginModal"></i>
            <%end%>
          </div>

          <div class="recipe-index-textbox">
              <%=link_to recipe do%>
                <div class="recipe-index-title linkto"><%=recipe.title%></div>
              <%end%>
              <div class="recipe-index-text">
                <div class="recipe-index-text-allergy"><%=recipe.allergyfor%></div>
                
                <div class="d-flex justify-content-between">
                  <div class="recipe-index-text-2">알레르기 보유자를 위한 <%=recipe.title%></div>
                  <div class="recipe-index-user">
                  by <%=recipe.name%>
                  </div>
                </div>
              </div>
              
          </div>
        </div>
      </div>
    <%end%>
  </div>


  <div class="d-flex justify-content-center container">
    <div class="recipe-new-button w-100 d-flex justify-content-between">
      <div></div>

      <div>   
      <%= paginate @recipes%>
      </div>

      <%if user_signed_in?%>
        <%= button_to '레시피 작성', new_recipe_path, :class => "btn btn-search", :method=>'get' %>
      <%else %>
        <span data-toggle="modal" data-target="#loginModal" class="btn btn-search">레시피 작성</span>
      <%end%>
    </div>
  </div>

</div>




<%if !user_signed_in?%>
        <%= render 'layouts/loginModal'%>
<%end%>





<script>

  var tagarray = [];
  $(".recipe-index-search-tag").click(function(){
    var key = $(this).html();
    key = key.split('&nbsp;')[1]
  
    if($(this).hasClass("allergy-tag-selected")){
      $(this).removeClass("allergy-tag-selected");
      tagarray.splice(tagarray.indexOf(key),1);
    }
    else{
      $(this).addClass("allergy-tag-selected");
      tagarray.push(key);
    }

    var idx = 0;
    var length = tagarray.length;
    var tagadd = '';
    for(;idx<length;idx++){
      tagadd+='#'+tagarray[idx]+' '
    }
    $(".recipe-index-search-input").val(tagadd);
  })

  

  if('<%=user_signed_in?%>'==="true"){
    $(".recipe-index-bookmark").click(function(){
        $recipeid = $(this).siblings("div.recipe-index-id-bookmark").html();
        $likeicon = $(this);
        $.ajax({
            async : true,
            data : {id: $recipeid},
            type : "GET",
            url : "/follows/recipefollow",
            success : function(data){
                $likeicon.toggleClass('far');
                $likeicon.toggleClass('fas');
            }
        })
    });
  }
</script>

app/views/recipes/new.html.erb
<%# <h1>New Recipe</h1> %>

<%#= render 'form', recipe: @recipe %>

<%#= link_to 'Back', recipes_path %>
<div class="w-100 d-flex justify-content-center">
    <div class="big-title recipe-new-ready">레시피 작성하기는 준비 중인 기능입니다. 곧 만나요!</div>
</div>